//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.Data.ILR._1819.ValdationErrors.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using ESFA.DC.Data.ILR._1819.ValdationErrors.Model.Interfaces;
    
    public partial class ValidationErrors : DbContext, IValidationErrors
    {
        public ValidationErrors()
            : base("name=ValidationErrors")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Rule> Rules { get; set; }
    }
}
